function convert_derived_pp()
	% This function takes in pp_master as generated by assemble_master_pp
	% It then converts it into derived_pp for use by db_derived_fit
	load pp_master

	% Now go through spectra and assemble
	for j = 1:size(pp,1) % for each spectrum
		output(j) = get_spec_analysis(pp_f,pp(j,:)); 
	end

	% Now create a new pp
	features = {'int_delta','int_theta','int_alpha','int_sigma','int_beta','alpha_str','sigma_str','beta_str'};

	pp = zeros(length([output.(features{1})]),length(features));
	
	for j = 1:length(features)
		pp(:,j) = [output.(features{j})];
	end

	save derived_pp pp features fitted_state states xyz